apiVersion: v1
kind: Pod
metadata:
  name: simplepod1
spec:
  containers:
    - name: cont1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: simplepod2
spec:
  containers:
    - name: cont2
      image: nginx:alpine
